Customers can select a pickup date and time
ethanschreur/kids-krafts pull request #58
Opened 2021-04-17 17:15 UTC by ethanschreur

2021-04-25 06:48 UTC, alexkayabula requested changes

2021-04-25 06:48 UTC, alexkayabula commented on app/helper.py
> +    return month_header
@ethanschreur please add concise comments to all these functions describing their use in the application.

2021-04-25 15:11 UTC, ethanschreur commented
Should be ready for review now.

2021-04-25 18:50 UTC, alexkayabula commented
I am going to review it later on and get back to you.

On Sun, Apr 25, 2021 at 6:11 PM Ethan Schreur ***@***.***>
wrote:

> Should be ready for review now.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/ethanschreur/kids-krafts/pull/58#issuecomment-826340239>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHQFNIWRQHAAFOY4POGGL63TKQWJXANCNFSM43DIURFA>
> .
>

2021-04-27 12:31 UTC, alexkayabula approved these changes
LGTM.

2021-04-27 12:31 UTC, merged